name: CI

on:
  pull_request:
    branches: master

jobs:
  build:

    runs-on: ubuntu-latest

    strategy:
      matrix:
        node-version: [14.x]

    steps:
      - name: Checkout repository
        uses: actions/checkout@v2

      - name: Set up Node.js ${{ matrix.node-version }}
        uses: actions/setup-node@v1
        with:
          node-version: ${{ matrix.node-version }}

      - name: Install dependencies
        run: npm install
      - name: Run Lint
        run: npm run lint
      - name: Run Prettier
        run: npm run prettier
      - name: Run tests
        run: npm run test
        env:
          ci: true
      - name: build
        run: npm run build